### ISSUE TITLE
Error when loading the product template in Metadata Management UI

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2874]
Uncaught (in promise) Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
    at invariant (webpack-internal:///./node_modules/fbjs/lib/invariant.js:42:15)
    at Object.addComponentAsRefTo (webpack-internal:///./node_modules/react-dom/lib/ReactOwner.js:66:36)
    at attachRef (webpack-internal:///./node_modules/react-dom/lib/ReactRef.js:21:16)
    at Object.ReactRef.attachRefs (webpack-internal:///./node_modules/react-dom/lib/ReactRef.js:40:5)
    at ReactDOMComponent.attachRefs (webpack-internal:///./node_modules/react-dom/lib/ReactReconciler.js:21:12)
    at CallbackQueue.notifyAll (webpack-internal:///./node_modules/react-dom/lib/CallbackQueue.js:74:22)
    at ReactReconcileTransaction.close (webpack-internal:///./node_modules/react-dom/lib/ReactReconcileTransaction.js:78:26)
    at ReactReconcileTransaction.closeAll (webpack-internal:///./node_modules/react-dom/lib/Transaction.js:207:25)
    at ReactReconcileTransaction.perform (webpack-internal:///./node_modules/react-dom/lib/Transaction.js:154:16)
    at ReactUpdatesFlushTransaction.perform (webpack-internal:///./node_modules/react-dom/lib/Transaction.js:141:20)

fyi @maxceem @RishiRajSahu

**Comment by vikasrohit** [comment]
More info:

This happens only when the template has file upload component in its template e.g. http://connect.topcoder-dev.com/metadata/productTemplates/20
