### ISSUE TITLE
Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2921]
### Expected behavior
Should not throw error in console

### Actual behavior
For certain use case, it is throwing the mentioned error and it is reported by Sentry

### Screenshot/screencast

```
TypeError: Cannot read property 'title' of undefined
  at ? (/main.aec5eb37545a88aa5118.js:249:205364)
  at Array.map(<anonymous>)
  at t.value(/main.aec5eb37545a88aa5118.js:249:205152)
  at l._renderValidatedComponentWithoutOwnerOrContext(/main.aec5eb37545a88aa5118.js:114:43176)
  at l._renderValidatedComponent(/main.aec5eb37545a88aa5118.js:114:43283)
  at l.performInitialMount(/main.aec5eb37545a88aa5118.js:114:39166)
  at l.mountComponent(/main.aec5eb37545a88aa5118.js:114:38212)
  at Object.mountComponent(/main.aec5eb37545a88aa5118.js:28:99911)
  at Object.updateChildren(/main.aec5eb37545a88aa5118.js:114:36096)
  at Z._reconcilerUpdateChildren(/main.aec5eb37545a88aa5118.js:114:33265)
  at Z._updateChildren(/main.aec5eb37545a88aa5118.js:114:34230)
  at Z.updateChildren(/main.aec5eb37545a88aa5118.js:114:34128)
  at Z._updateDOMChildren(/main.aec5eb37545a88aa5118.js:114:25579)
  at Z.updateComponent(/main.aec5eb37545a88aa5118.js:114:23756)
  at Z.receiveComponent(/main.aec5eb37545a88aa5118.js:114:23309)
  at Object.receiveComponent(/main.aec5eb37545a88aa5118.js:28:100307)
  at l._updateRenderedComponent(/main.aec5eb37545a88aa5118.js:114:42651)
  at l._performComponentUpdate(/main.aec5eb37545a88aa5118.js:114:42408)
  at l.updateComponent(/main.aec5eb37545a88aa5118.js:114:41686)
  at l.receiveComponent(/main.aec5eb37545a88aa5118.js:114:40813)
  at Object.receiveComponent(/main.aec5eb37545a88aa5118.js:28:100307)
  at l._updateRenderedComponent(/main.aec5eb37545a88aa5118.js:114:42651)
  at l._performComponentUpdate(/main.aec5eb37545a88aa5118.js:114:42408)
  at l.updateComponent(/main.aec5eb37545a88aa5118.js:114:41686)
  at l.receiveComponent(/main.aec5eb37545a88aa5118.js:114:40813)
  at Object.receiveComponent(/main.aec5eb37545a88aa5118.js:28:100307)
  at Object.updateChildren(/main.aec5eb37545a88aa5118.js:114:35977)
  at Z._reconcilerUpdateChildren(/main.aec5eb37545a88aa5118.js:114:33265)
  at Z._updateChildren(/main.aec5eb37545a88aa5118.js:114:34230)
  at Z.updateChildren(/main.aec5eb37545a88aa5118.js:114:34128)
  at Z._updateDOMChildren(/main.aec5eb37545a88aa5118.js:114:25579)
  at Z.updateComponent(/main.aec5eb37545a88aa5118.js:114:23756)
  at Z.receiveComponent(/main.aec5eb37545a88aa5118.js:114:23309)
  at Object.receiveComponent(/main.aec5eb37545a88aa5118.js:28:100307)
  at l._updateRenderedComponent(/main.aec5eb37545a88aa5118.js:114:42651)
  at l._performComponentUpdate(/main.aec5eb37545a88aa5118.js:114:42408)
  at l.updateComponent(/main.aec5eb37545a88aa5118.js:114:41686)
  at l.receiveComponent(/main.aec5eb37545a88aa5118.js:114:40813)
  at Object.receiveComponent(/main.aec5eb37545a88aa5118.js:28:100307)
  at l._updateRenderedComponent(/main.aec5eb37545a88aa5118.js:114:42651)
  at l._performComponentUpdate(/main.aec5eb37545a88aa5118.js:114:42408)
  at l.updateComponent(/main.aec5eb37545a88aa5118.js:114:41686)
  at l.performUpdateIfNecessary(/main.aec5eb37545a88aa5118.js:114:41029)
  at Object.performUpdateIfNecessary(/main.aec5eb37545a88aa5118.js:28:100489)
  at b(/main.aec5eb37545a88aa5118.js:28:12988)
  at d.perform(/main.aec5eb37545a88aa5118.js:28:166865)
  at y.perform(/main.aec5eb37545a88aa5118.js:28:166865)
  at y.perform(/main.aec5eb37545a88aa5118.js:28:13450)
  at Object._ [as flushBatchedUpdates](/main.aec5eb37545a88aa5118.js:28:13619)
  at closeAll(/main.aec5eb37545a88aa5118.js:28:167453)
```

More specific code block identified by Sentry:

```
{snip} er";var s=b()(e.roles,function(e){return e.value===t.role}).title;return O.a.createElement("div",{key:m,className:"project-member-layout "+( {snip}
```

--

#### Environment
- OS: Mac OS X 10.13.6
- Browser (w/version): Chrome 72.0.3626
- User role (client, copilot or manager): Manager
- Account used: N/A

**Comment by vikasrohit** [comment]
Patched and verified on production.
