### ISSUE TITLE
Getting an error while trying to attach a file to the "Assets Library"

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3814]
### Expected behavior
User should be able to attach a file to the library without an issue.

### Actual behavior
Getting an error while trying to attach a file to the "Assets Library"

### Steps to reproduce the problem
- Login as Manager
- Click on a project from the project listing page
- Click "Assets Library"
- Click Files > Add New > Browse a file > Upload
- Click 'All project members'

**Browser console error:**
```
api.topcoder-dev.com/v5/projects/9018/attachments:1 Failed to load resource: the server responded with a status of 500 ()
00:42:37.621 main.361369fafcb93bf04c3d.js:130 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (main.361369fafcb93bf04c3d.js:130)
    at e.exports (main.361369fafcb93bf04c3d.js:223)
    at XMLHttpRequest.f.<computed> (main.361369fafcb93bf04c3d.js:130)
```

**API Response:**
```
{"message":"Request failed with status code 400","debug":"Error: Request failed with status code 400\n    at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/lib/adapters/http.js:236:11)\n    at emitNone (events.js:110:20)\n    at IncomingMessage.emit (events.js:207:7)\n    at endReadableNT (_stream_readable.js:1045:12)\n    at /usr/src/app/node_modules/async-listener/glue.js:188:31\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n    at process.fallback (/usr/src/app/node_modules/async-listener/index.js:565:15)"}
```

### Screenshot/screencast

https://www.screencast.com/t/q5O8V8KyTT

![image](https://user-images.githubusercontent.com/42398485/77841218-eb792c80-7154-11ea-948e-edfebe812f54.png)

--

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.149 (Official Build) (64-bit)
- User role (client, copilot or manager): Manager
- Account used:  topcoderconnect+Customer@gmail.com

**Comment by vikasrohit** [comment]
@maxceem I think this issue is happening because of we renamed the `filePath` to `path` in attachments model which in turn we are passing to file api to retrieve the signed download url which is throwing 400 because of renamed `filePath` to `path` as it is expecting `filePath` not `path`.

**Comment by maxceem** [comment]
@codejamtc this is fixed and ready for testing on DEV.

**Comment by codejamtc** [comment]
https://www.screencast.com/t/YJn9yPi6Lc

**Comment by coderhacker** [comment]
Verified on dev working as expected.

**Comment by codejamtc** [comment]
Verified in `Prod`: 🆗 Pass
**User:** CustomerUser

https://monosnap.com/file/tTN3S7rIsjXFRFqd1mQIeACiNbxZcP
